spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "spin-hello-world"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "target/wasm32-wasi/release/http_rust.wasm"
description = "A simple component that returns hello."
ai_models = ["llama2-chat"]
[component.hello.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
